import Head from "next/head";
import Layout from "../components/Layout/Layout";
import Header from "../components/Header";
import HomePage from "../components/HomePage";
import Footer from "../components/Footer";
import Services from "../components/Services";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Layout>
          <Header />
          <HomePage />
          <Services />
          <Contact />
          <Footer />
        </Layout>
      </main>
    </>
  );
}
